---
abstract: 'Email::Abstract wrapper for Qpsmtpd::Transaction'
author:
  - 'Naoki Tomita <tomita@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Abstract-QpsmtpdTransaction
no_index:
  directory:
    - inc
    - t
requires:
  Email::Abstract: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
